#!/bin/bash
#deklarasikan array [explicit declration]
declare -a angka

#clear
i=0;
while [ $i -le 4 ];
do
   let isi=$i*2;
   angka[$i]=$isi;
   let i=$i+1;
done

#menampilkan semua elemen array
echo ${angka[@]}
