print('-' * 35)
print('Tugas 1 Sisop Kelas-A')
print('-' * 35)
print('Nama : Aisyah Kirana Putri Isyanto')
print('NPM : 2108310065')
print('-' * 35)
print('notes: ')
print('-' * 35)
print('Halo duniaku')
print('Ini adalah skrip Bash pertamaku di Linux')
