print('-' * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama : Aisyah Kirana Putri Isyanto')
print('NPM : 21083010065')
print('-' * 35)
print'notes: ')
print('Halo dunia!')
print('Ini adalah skrip Bash pertamaku di Linux!')
